### ISSUE TITLE
Micro Wake Word not working anymore

### ISSUE THREAD

**Issue by AtrejaAlwinnen** [joshuaboniface/supersensor#1]
Hi,
until a few weeks ago I was running your sensor with the Micro_wake_word as a test setup.

As that worked well, I have now bought all the hardware and soldered everything together, unfortunately I can't get the Micro_wake_word thing to work anymore.
The hardware is OK, with openwakeword everything works fine.
However, as I run HA on a Pi, openwakeword generates about 20% CPU usage at all time.

The first error I got was:

> INFO ESPHome 2024.12.4
> 
> INFO Reading configuration /config/esphome/supersensor1-24d9e8.yaml...
> INFO Updating https://github.com/esphome/esphome.git@pull/5230/head
> WARNING The selected ESP-IDF framework version is not the recommended one. If there are connectivity or build issues please remove the manual version.
> WARNING The selected ESP-IDF framework version is not the recommended one. If there are connectivity or build issues please remove the manual version.
> Failed config
> 
> micro_wake_word: [source /config/esphome/supersensor1-24d9e8.yaml:293]
>   
>   'models' is a required option for [micro_wake_word].
>   
>   The model parameter has moved to be a list element under the models parameter.
>   model: hey_jarvis
>   on_wake_word_detected: 
>     then: 
>       - voice_assistant.start: 
>           wake_word: !lambda |-
>             return wake_word;

so i changed your code to:

> micro_wake_word:
>   vad:
>   models:
>     - model: hey_jarvis
>   on_wake_word_detected:
>     then:
>       - voice_assistant.start:
>           wake_word: !lambda return wake_word;

and also enabled: 

> voice_assistant:
>   microphone: mic
>   use_wake_word: true

Now the code compiles and I can flash it to the ESP, but the Micro_wake_word function doesn't seem to work.

![Image](https://github.com/user-attachments/assets/b3aed202-747e-4db4-a8fb-11530dbdcafe)

the wake word button is also grayed out.

Do you have any idea what went wrong?

Greetings
Atreja

**Comment by joshuaboniface** [comment]
I don't use MWW, so I can't be much help. It's possible this is related to the pinning of the ESP-IDF framework I did a little while ago to get this to work with ESPHome 2024.12.x, but I'm not certain.

**Comment by AtrejaAlwinnen** [comment]
Hi, and thanks for the answer.
I was afraid that you wouldn't be able to help me, since the part in the .yaml had already been commented out with the note that it wasn't working properly.
With the Supersensor version 1.1 and before 2024.12, MWW worked for me without any problems.
Is there a way to undo the change? 
Other than using the old HomeAssistant version?
Unfortunately, your really great sensor is of no use to me without MWW. :/

**Comment by joshuaboniface** [comment]
As you note, I never did get MWW working myself. First thing is to see if you can bump the ESP-IDF versions I set - as long as the rest of the sensor code compiles whatever version is used should be fine. Beyond that pinning to the old version might, unfortunately, be required for now.

**Comment by joshuaboniface** [comment]
I'll see if I can spend some time this weekend digging into it and keep you posted here.

**Comment by AtrejaAlwinnen** [comment]
That would be really great and would be very happy about it. :)

**Comment by joshuaboniface** [comment]
I just pushed some commits to restore things to the Arduino framework (so not ESP-IDF), as well as switch to the BSEC2 library for the IAQ sensor. Feel free to give this version a try with OWW and let me know how it goes.

**Comment by AtrejaAlwinnen** [comment]
The code compiles without problems and the sensor runs well under ESPHome 2024.12.4
Open Wake Word also works without problems.
Unfortunately, the Miocro Wake Word still doesn't work.
The section for this no longer corresponds to the current syntax and when I change it to the syntax specified on the ESPHome website, I get the following error message:

> INFO ESPHome 2024.12.4
> INFO Reading configuration /config/esphome/supersensor.yaml...
> INFO Updating https://github.com/esphome/esphome.git@pull/5230/head
> Failed config
> 
> micro_wake_word: [source /config/esphome/supersensor.yaml:288]
>   
>   This feature is only available with frameworks ['esp-idf'].
>   vad: 
>   models: 
>     - model: okay_nabu
>     - model: hey_mycroft
>   on_wake_word_detected: 
>     then: 
>       - voice_assistant.start: 
>           wake_word: !lambda |-
>             return wake_word;

**Comment by joshuaboniface** [comment]
I just realized that myself. Seems you need ESP-IDF to do micro wake word, but need Arduino to do BSEC2.

I'm currently testing how well the BSEC2 library works with the BME680's, so I might go back if it doesn't. Unfortunately though that kinda precludes OWW support for me at this time. If you want to prioritize OWW, you can try switching back to ESP-IDF (i.e. use the tag 1.2 version) but then I think we're back to the beginning again where it just wasn't working.

**Comment by joshuaboniface** [comment]
Well the "good" news is BSEC2 is just as utterly useless for IAQ as BSEC1 was, so I guess we can go back to ESP-IDF. I'll push a new version shortly.

**Comment by joshuaboniface** [comment]
I've done some testing myself and I can definitely replicate this. Adding some debug logging, on 4.4.8 it simply doesn't work at all with no indication as to why. I also went through and tested various 5.x releases of ESP-IDF and none of them compile successfully. So I think we're stuck until ESPHome puts out a fixed release that properly supports ESP-IDF 5.x.

I would suggest - if one doesn't already exist - opening an issue on the ESPHome GitHub about MWW not working on 4.4.8. Feel free to reference this issue. Perhaps they can provide a pointer.

**Comment by AtrejaAlwinnen** [comment]
Thank you very much for your efforts. 
I also had no success with the 5.x releases. 
I'll take a look at ESPhome and if there is nothing there about MWW I'll open an issue.

**Comment by joshuaboniface** [comment]
I finally got some time to look into this, and from my testing so far I'm seeing no problems with MicroWakeWord on ESPHome 2025.5.

```
diff --git a/supersensor.yaml b/supersensor.yaml
index f5bdf48..5be4c3c 100644
--- a/supersensor.yaml
+++ b/supersensor.yaml
@@ -371,16 +371,15 @@ interval:
             App.safe_reboot();
           }
 
-# Add optional microWakeWord support (on-device wake word)
-# Doesn't work well as of 2024-07-04 so leave disabled
-#micro_wake_word:
-#  model: hey_jarvis
-#  on_wake_word_detected:
-#    then:
-#      - voice_assistant.start:
-#          wake_word: !lambda return wake_word;
-
-# Include the Espressif Audio Development Framework for VAD support
+micro_wake_word:
+  vad:
+  models:
+    - model: hey_jarvis
+  on_wake_word_detected:
+    then:
+      - voice_assistant.start:
+          wake_word: !lambda return wake_word;
+
 esp_adf:
 external_components:
   - source: github://pr#5230
```

Enabled like so, ensured I removed the Wake Word engine from the Assist pipeline, restarted everything, and it "just works".

I'm wondering were you able to get it working with the HomeAssistant-side wake words, with everything working?

**Comment by joshuaboniface** [comment]
Sorry I mistook the verison, I am indeed on 2025.4.1.

You might want to adjust the gain, I believe there's an option for that. But in my configuration I'm setting that within the voice_assistant and it seems to "just work" fine.

Also worth noting that the only ESP32 I've ever used for this is the ESP32-WROOM-32D; I haven't tried any others and thus can't really provide assistance with those.

**Comment by joshuaboniface** [comment]
I believe I ended up solving this. While I've not backported the fixes to 1.x here (I've moved on to a 2.x design, see the README), the code itself should be easily backported.

In short, I removed the ESP-ADF component, as this is no longer properly supported.

I then ensured I was actually setting the microphone channel to the right one.

And suddenly everything started working perfectly.
